[General]

passwordAllowEmpty=false
font=JetBrainsMono Nerd Font Mono

# Passwork text
passwordCharacter=
passwordMask=true
passwordFontSize=28
passwordCursorColor=#f0ebe0
passwordTextColor=#f0ebe0
passwordInputCursorVisible=false
cursorBlinkAnimation=false

# Password input box
passwordInputFixedWidth=650
passwordInputFixedHeight=100
passwordInputBackground=#1f1f28
passwordInputRadius=6
passwordInputBorderWidth=4
passwordInputBorderColor=#f0ebe0

# wrong password
wrongPasswordBorderRadius=0
wrongPasswordBorderColor=#e46876


# Sessions choose label
showSessionsByDefault=false
sessionsFontSize=24

# Users choose label
showUsersByDefault=false
usersFontSize=32

# Background image
background=0-ship-at-sea.jpg
backgroundFillMode=aspect

# Default text color for all labels
basicTextColor=#f0ebe0

# Radius of background blur
blurRadius=70
